version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: k8s_assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=k8s_assignment;Username=postgres;Password=yourpassword
    depends_on:
      - db
volumes:
  pgdata:
